spring:
    application:
        name: sberx-guide
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test1
        username: postgres
        password: root
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                default_schema: public
                temp:
                    use_jdbc_metadata_defaults: false

